
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author calva
 */
public class DamkarPage extends javax.swing.JFrame {
    public user pengguna;
    /**
     * Creates new form KontakdanLokasi
     */
    ArrayList<damkar> fireStations = new ArrayList<>();
    private damkar nearestStation;
    
    
    /**
     * Creates new form KontakdanLokasi
     */
    private void addFireStations() {
        fireStations.add(new damkar("Unit Bandung Selatan", "515151", "Jl. Suramadu", 98.54, -101.02));
        fireStations.add(new damkar("Unit Bandung Timur", "525252", "Jl. Gatot Subroto", 100.64, -95.99));
        fireStations.add(new damkar("Unit Jabar 2", "535353", "Jl. Otista", 90.25, -97.36));
        fireStations.add(new damkar("Unit Mobile 1", "545454", "Jl. Pasteur", 106.78, -89.87));

    }
    
    public DamkarPage(user pengguna) {
        initComponents();
        this.pengguna = pengguna;
        addFireStations();
        damkar nearest = getNearest(fireStations);
        address.setText(nearest.alamat);
        phone.setText(nearest.phoneNumber);
        unit.setText(nearest.station);
    }
    
    private damkar getNearest(ArrayList<damkar> fireStations) {
        double nearest = 99999999;
        double distance = 0;
        
        
        for(damkar x : fireStations) {
            distance = distance(pengguna.getLatitude(), pengguna.getLongitude(), x.latitude, x.longitude);
            
            
            if (distance < nearest) {
                nearest = distance;
                nearestStation = x;
            }
        }
        return nearestStation;
    }
    
    private double distance(double lat1, double lon1, double lat2, double lon2) {
      double theta = lon1 - lon2;
      double dist = Math.sin(deg2rad(lat1)) * Math.sin(deg2rad(lat2)) + Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * Math.cos(deg2rad(theta));
      dist = Math.acos(dist);
      dist = rad2deg(dist);
      dist = dist * 60 * 1.1515;
      dist = dist * 0.8684;
      
      return (dist);
    }
    
    private double deg2rad(double deg) {
      return (deg * Math.PI / 180.0);
    }
    
    private double rad2deg(double rad) {
      return (rad * 180.0 / Math.PI);
    }
    
    public DamkarPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        telpLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        phone = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        unit = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Pemadam Kebakaran");

        telpLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        telpLabel.setText("No. Telp   : ");

        addressLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addressLabel.setText("Alamat  :");

        kembali.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone.setText("012345678910");

        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        address.setText("bandung, Jawa Barat");

        unit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        unit.setText("bandung, Jawa Barat");

        addressLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addressLabel1.setText("Unit Pemadam  :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLabel)
                                .addGap(18, 18, 18)
                                .addComponent(address))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telpLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(unit))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kembali)))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel1)
                    .addComponent(unit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telpLabel)
                    .addComponent(phone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(kembali)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        this.toBack();
        setVisible(false);
        new DaftarLayanan().toFront();
        new DaftarLayanan().setState(java.awt.Frame.NORMAL);        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontakdanLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontakdanLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontakdanLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontakdanLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DamkarPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel telpLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel unit;
    // end of variables declaration//GEN-END:variables
}
